/**
 * Orchestrator Extension - Full-cycle project planning and execution
 *
 * WORKFLOW (single command):
 *   /plan <description> → 5 sequential agent phases → each with its own model
 *
 * The orchestrator uses event-driven phase chaining:
 *   1. Send phase 1 message with model A
 *   2. Detect when agent goes idle (output event + polling)
 *   3. Switch to model B, send phase 2
 *   4. Repeat until all 5 phases complete
 *
 * Commands:
 *   /plan   — Full workflow: plan + execute with agents
 *   /run    — Re-execute an existing plan
 *   /plans  — List plans and their execution status
 */

import { Type } from "@sinclair/typebox";
import type { ExtensionAPI } from "phi-code";
import { writeFile, mkdir, readdir, readFile } from "node:fs/promises";
import { join } from "node:path";
import { existsSync, readFileSync } from "node:fs";
import { homedir } from "node:os";

// ─── Types ───────────────────────────────────────────────────────────────

interface TaskDef {
	title: string;
	description: string;
	agent?: string;
	priority?: string;
	dependencies?: number[];
	subtasks?: string[];
}

// ─── Extension ───────────────────────────────────────────────────────────

export default function orchestratorExtension(pi: ExtensionAPI) {
	const plansDir = join(process.cwd(), ".phi", "plans");

	async function ensurePlansDir() {
		await mkdir(plansDir, { recursive: true });
	}

	function timestamp(): string {
		return new Date().toISOString().replace(/[:.]/g, "-").replace("T", "_").slice(0, 19);
	}

	// ─── Plan File Generators ────────────────────────────────────────

	function generateSpec(p: {
		title: string; description: string; goals: string[]; requirements: string[];
		architecture?: string[]; constraints?: string[]; successCriteria?: string[]; tasks: TaskDef[];
	}): string {
		let spec = `# ${p.title}\n\n`;
		spec += `**Created:** ${new Date().toLocaleString()}\n\n`;
		spec += `## Description\n\n${p.description}\n\n`;
		spec += `## Goals\n\n`;
		p.goals.forEach((g, i) => { spec += `${i + 1}. ${g}\n`; });
		spec += "\n## Requirements\n\n";
		p.requirements.forEach(r => { spec += `- ${r}\n`; });
		spec += "\n";
		if (p.architecture?.length) {
			spec += `## Architecture\n\n`;
			p.architecture.forEach(a => { spec += `- ${a}\n`; });
			spec += "\n";
		}
		if (p.constraints?.length) {
			spec += `## Constraints\n\n`;
			p.constraints.forEach(c => { spec += `- ${c}\n`; });
			spec += "\n";
		}
		if (p.successCriteria?.length) {
			spec += `## Success Criteria\n\n`;
			p.successCriteria.forEach(s => { spec += `- [ ] ${s}\n`; });
			spec += "\n";
		}
		spec += `## Task Overview\n\n| # | Task | Agent | Priority | Dependencies |\n|---|------|-------|----------|-------------|\n`;
		p.tasks.forEach((t, i) => {
			const deps = t.dependencies?.map(d => `#${d}`).join(", ") || "—";
			spec += `| ${i + 1} | ${t.title} | ${t.agent || "code"} | ${t.priority || "medium"} | ${deps} |\n`;
		});
		spec += `\n---\n*Generated by Phi Code Orchestrator*\n`;
		return spec;
	}

	function generateTodo(title: string, tasks: TaskDef[]): string {
		let todo = `# TODO: ${title}\n\n`;
		todo += `**Created:** ${new Date().toLocaleString()}\n`;
		todo += `**Tasks:** ${tasks.length}\n**Status:** executing\n\n`;
		tasks.forEach((t, i) => {
			const agentTag = t.agent ? ` [${t.agent}]` : "";
			const prioTag = t.priority === "high" ? " 🔴" : t.priority === "low" ? " 🟢" : " 🟡";
			const depsTag = t.dependencies?.length ? ` (after #${t.dependencies.join(", #")})` : "";
			todo += `## Task ${i + 1}: ${t.title}${prioTag}${agentTag}${depsTag}\n\n- [ ] ${t.description}\n`;
			if (t.subtasks) t.subtasks.forEach(st => { todo += `  - [ ] ${st}\n`; });
			todo += "\n";
		});
		todo += `---\n\n## Progress\n\n- Total: ${tasks.length} tasks\n`;
		todo += `- High priority: ${tasks.filter(t => t.priority === "high").length}\n`;
		todo += `- Agents: ${[...new Set(tasks.map(t => t.agent || "code"))].join(", ")}\n`;
		return todo;
	}

	// ─── Orchestrate Tool — Structured planning with prompt-architect pattern ───

	pi.registerTool({
		name: "orchestrate",
		label: "Project Orchestrator",
		description: "Create a structured project plan with spec, todo, and task breakdown. Forces the model to decompose the project into goals, requirements, architecture, constraints, and success criteria before execution.",
		promptSnippet: "Plan + structure projects using the prompt-architect pattern. Each task gets [CONTEXT] → [TASK] → [FORMAT] → [CONSTRAINTS].",
		promptGuidelines: [
			// NOTE: The old guideline "When asked to plan or build a project, call the orchestrate tool"
			// was REMOVED because it hijacked the /plan command flow. The orchestrate tool is now
			// only called explicitly or when the model decides structured planning is needed outside of /plan.
			"IMPORTANT: Do NOT call orchestrate during /plan orchestration phases. The /plan command handles its own workflow.",
			"Structure each task description using the prompt-architect pattern: [CONTEXT] what exists and why → [TASK] what to do specifically → [FORMAT] expected output → [CONSTRAINTS] rules and limitations.",
			"Assign agent types strategically: 'explore' (read-only analysis), 'plan' (architecture), 'code' (implementation), 'test' (write+run tests), 'review' (quality audit).",
			"Set dependencies to maximize parallelism: tasks without dependencies run simultaneously.",
			"Set priority=high for critical-path tasks, medium for standard work, low for nice-to-haves.",
		],
		parameters: Type.Object({
			title: Type.String({ description: "Concise project title" }),
			description: Type.String({ description: "Full project description: what to build, why, and any relevant context" }),
			goals: Type.Union([Type.Array(Type.String()), Type.String()], { description: "Measurable project goals (what success looks like)" }),
			requirements: Type.Union([Type.Array(Type.String()), Type.String()], { description: "Technical and functional requirements" }),
			architecture: Type.Optional(Type.Union([Type.Array(Type.String()), Type.String()], { description: "Architecture decisions, tech stack choices, trade-offs" })),
			tasks: Type.Array(
				Type.Object({
					title: Type.String({ description: "Clear, action-oriented task title" }),
					description: Type.String({ description: "SELF-CONTAINED task description. Include ALL context the sub-agent needs." }),
					agent: Type.Optional(Type.String({ description: "Agent type: explore, plan, code, test, review" })),
					priority: Type.Optional(Type.String({ description: "high, medium, low" })),
					dependencies: Type.Optional(Type.Array(Type.Number(), { description: "Task numbers this depends on (1-indexed)" })),
					subtasks: Type.Optional(Type.Array(Type.String(), { description: "Specific sub-steps within this task" })),
				}),
				{ description: "Ordered list of tasks" }
			),
			constraints: Type.Optional(Type.Union([Type.Array(Type.String()), Type.String()], { description: "Hard constraints: things to avoid, rules" })),
			successCriteria: Type.Optional(Type.Union([Type.Array(Type.String()), Type.String()], { description: "How to verify the project is complete" })),
		}),

		async execute(_toolCallId, params, _signal, _onUpdate, _ctx) {
			// Block if /plan orchestration is active — prevent hijacking
			if (orchestrationActive) {
				return {
					content: [{ type: "text", text: "⚠️ Orchestration is already active via /plan. Do NOT call orchestrate during /plan phases. Follow the phase instructions instead." }],
				};
			}

			const raw = params as any;

			// Normalize string fields to arrays
			const toArray = (v: any): string[] => {
				if (!v) return [];
				if (Array.isArray(v)) return v;
				if (typeof v === "string") return v.split("\n").map((s: string) => s.replace(/^[-•*]\s*/, "").trim()).filter(Boolean);
				return [];
			};

			const p = {
				title: raw.title as string,
				description: raw.description as string,
				goals: toArray(raw.goals),
				requirements: toArray(raw.requirements),
				architecture: raw.architecture ? toArray(raw.architecture) : undefined,
				tasks: raw.tasks as TaskDef[],
				constraints: raw.constraints ? toArray(raw.constraints) : undefined,
				successCriteria: raw.successCriteria ? toArray(raw.successCriteria) : undefined,
			};

			try {
				await ensurePlansDir();
				const ts = timestamp();
				const specFile = `spec-${ts}.md`;
				const todoFile = `todo-${ts}.md`;

				// Generate and write structured plan files
				const spec = generateSpec(p);
				const todo = generateTodo(p.title, p.tasks);
				await writeFile(join(plansDir, specFile), spec, "utf-8");
				await writeFile(join(plansDir, todoFile), todo, "utf-8");

				const summary = `📋 **Project "${p.title}" — Structured plan created!**\n\n` +
					`**Spec:** \`${specFile}\` | **Todo:** \`${todoFile}\`\n\n` +
					`**Goals:** ${p.goals.length} | **Requirements:** ${p.requirements.length} | **Tasks:** ${p.tasks.length}\n\n` +
					`The spec and todo files are ready in \`.phi/plans/\`. ` +
					`Use \`/plan ${p.description.slice(0, 100)}\` to execute with the 5-phase orchestrator, ` +
					`or work through the tasks manually.`;

				return {
					content: [{ type: "text", text: summary }],
					details: { specFile, todoFile, taskCount: p.tasks.length },
				};
			} catch (error) {
				return {
					content: [{ type: "text", text: `Orchestration failed: ${error}` }],
					details: { error: String(error) },
				};
			}
		},
	});

	// ─── Orchestration State ─────────────────────────────────────────

	interface AgentDef {
		name: string;
		tools: string[];
		systemPrompt: string;
	}

	interface OrchestratorPhase {
		key: string;
		label: string;
		model: string;
		fallback: string;
		agent: AgentDef | null;
		instruction: string;
	}

	let phaseQueue: OrchestratorPhase[] = [];
	let orchestrationActive = false;
	let activeAgentPrompt: string | null = null;
	let activeAgentTools: string[] | null = null;
	let savedTools: string[] | null = null;
	let phasePending = false; // true while waiting for a phase to complete
	let phaseTimeoutId: ReturnType<typeof setTimeout> | null = null;
	const MAX_PHASE_DURATION_MS = 10 * 60 * 1000; // 10 minutes per phase
	const MAX_TOOL_CALLS_PER_PHASE = 60; // Safety limit
	let phaseStartTime: number | null = null;

	/**
	 * Parse agent .md file with YAML frontmatter
	 */
	function loadAgentDef(name: string): AgentDef | null {
		const dirs = [
			join(process.cwd(), ".phi", "agents"),
			join(homedir(), ".phi", "agent", "agents"),
		];
		for (const dir of dirs) {
			const filePath = join(dir, `${name}.md`);
			try {
				const content = readFileSync(filePath, "utf-8");
				const fmMatch = content.match(/^---\s*\n([\s\S]*?)\n---\s*\n([\s\S]*)$/);
				if (!fmMatch) continue;
				const fields: Record<string, string> = {};
				for (const line of fmMatch[1].split("\n")) {
					const m = line.match(/^(\w+):\s*(.*)$/);
					if (m) fields[m[1]] = m[2].trim();
				}
				return {
					name: fields.name || name,
					tools: (fields.tools || "").split(",").map(t => t.trim()).filter(Boolean),
					systemPrompt: fmMatch[2].trim(),
				};
			} catch { continue; }
		}
		return null;
	}

	/**
	 * Load routing config and build phase queue with model assignments + agent definitions.
	 * Each phase now reads outputs from previous phases and writes structured outputs.
	 */
	function buildPhases(description: string): OrchestratorPhase[] {
		const routingPath = join(homedir(), ".phi", "agent", "routing.json");
		let routing: any = { routes: {}, default: { model: "default" } };
		try {
			routing = JSON.parse(readFileSync(routingPath, "utf-8"));
		} catch { /* no routing config */ }

		function getModel(routeKey: string): { preferred: string; fallback: string } {
			const route = routing.routes?.[routeKey];
			return {
				preferred: route?.preferredModel || routing.default?.model || "default",
				fallback: route?.fallback || routing.default?.model || "default",
			};
		}

		const explore = getModel("explore");
		const plan = getModel("plan");
		const code = getModel("code");
		const test = getModel("test");
		const review = getModel("review");

		const ts = timestamp();
		// Inject runtime info so agents can adapt to the host OS
		const shellNote = process.platform === 'win32'
			? `\nShell: bash (Git Bash), NOT cmd.exe. Always use Unix syntax: rm not del, test -f not if exist, / not \\\\`
			: '';
		const runtimeInfo = `\n\nRuntime: ${process.platform} (${process.arch})${shellNote}`;

		return [
			{
				key: "explore", label: "🔍 Phase 1 — EXPLORE", model: explore.preferred, fallback: explore.fallback,
				agent: loadAgentDef("explore"),
				instruction: `You are the EXPLORE agent. Analyze the project requirements and existing codebase.

**FIRST ACTION (MANDATORY):** Call \`memory_search\` with project-relevant keywords to check for prior context.

**Project Request:** ${description}

**Your tasks:**

**Parallelization:** When making multiple tool calls that don't depend on each other (e.g., memory_search + ontology_query, or reading 2+ files), call them IN PARALLEL in the same response. This is faster.

1. Call \`memory_search\` with project-relevant keywords (MANDATORY)
2. List all existing files and read key ones
3. Identify tech stack, patterns, and constraints
4. Create a STRUCTURED PROJECT BRIEF in \`.phi/plans/brief-${ts}.md\`:
   - Context: what exists now
   - Objective: what needs to be built
   - Requirements: specific features needed
   - Tech decisions: frameworks, patterns to use
   - Constraints: what to NOT break
5. **MANDATORY:** Write your findings to \`.phi/plans/explore-${ts}.md\` using the \`write\` tool. This file is READ by Phase 2 PLAN — if you skip it, the plan agent has no context. Do NOT skip this step.

**LAST ACTION (MANDATORY):** Call \`memory_write\` to save your exploration findings for downstream agents.

**Knowledge Graph:**
// TODO: ontology_batch_add for reducing API calls (currently single-item only)
After your analysis, use \`ontology_add\` to save key project entities AND their relations:
- Add entities for: the project, each major library, each module/directory
- Add relations between them: "uses", "contains", "depends_on", "implements"
- Example: entity "finance-tracker" (type: Project) → relation "uses" → entity "ink" (type: Library)
- ALWAYS create relations — entities without relations are useless

**Format for the project brief:**
\`\`\`markdown
## Project Brief

### Context
[Analyze what the user is asking for]

### Objective
[Clear, specific goal]

### Requirements
[Bullet list of what must be built]

### Tech Decisions
[Frameworks, patterns, architecture choices]

### Constraints
- Production-quality code, no placeholders
- Every function fully implemented
- Follow existing patterns if codebase exists
- [Any other specific constraints]
\`\`\`` + runtimeInfo,
			},
			{
				key: "plan", label: "📐 Phase 2 — PLAN", model: plan.preferred, fallback: plan.fallback,
				agent: loadAgentDef("plan"),
				instruction: `You are the PLAN agent. Design the architecture and create a detailed task list.

**Context Retrieval:**
1. Use \`ontology_query\` to retrieve all entities and relations from Phase 1
2. Use \`memory_search\` with project-relevant keywords to find existing notes
3. Use this knowledge to inform your plan

**Project Request:** ${description}

**Step 1:** Read \`.phi/plans/brief-*.md\` (created by the explore phase)
**Step 2:** Read \`.phi/plans/explore-*.md\` to understand the codebase analysis
**Step 3:** Design the architecture based on findings
**Step 4:** Create a DETAILED TODO LIST in \`.phi/plans/todo-${ts}.md\`:
   For each task:
   - Task number and title
   - Agent assignment (code/test)
   - Files to create/modify
   - Specific implementation details
   - Dependencies on other tasks

**Format for the todo list:**
\`\`\`markdown
# TODO: Project Tasks

## Task 1: [Task Title] [agent-type]
- [ ] Specific implementation details
- [ ] Files to create: path/to/file.ext
- [ ] Expected behavior
- Dependencies: None

## Task 2: [Task Title] [agent-type]
- [ ] Implementation details
- Dependencies: Task 1
\`\`\`

Before finishing, use \`memory_write\` to save your plan summary with relevant tags for future reference.` + runtimeInfo,
			},
			{
				key: "code", label: "💻 Phase 3 — CODE", model: code.preferred, fallback: code.fallback,
				agent: loadAgentDef("code"),
				instruction: `You are the CODE agent. Implement the complete project.

**Context Retrieval:**
1. Use \`memory_search\` with project keywords to find notes from previous phases
2. Use \`ontology_query\` to understand the project structure and dependencies
3. Use this context to guide implementation

**Project Request:** ${description}

**Step 1:** Read \`.phi/plans/brief-*.md\` for project context
**Step 2:** Read \`.phi/plans/todo-*.md\` to get your task list
**Step 3:** Implement EVERY task from the todo list, in order
**Step 4:** Write a progress report to \`.phi/plans/progress-${ts}.md\`

**Rules:**
- Create every file listed in the plan
- No placeholders, no TODOs, no stubs
- Every function must be fully implemented
- Follow the architecture from the plan
- Check off tasks in your progress report as you complete them

**Progress report format:**
\`\`\`markdown
# Progress Report

## Completed Tasks
- [x] Task 1: Description - DONE
- [x] Task 2: Description - DONE

## Files Created
- path/to/file1.ext - Purpose
- path/to/file2.ext - Purpose

## Implementation Notes
[Any important decisions or changes made]
\`\`\`

After implementation, use \`memory_write\` to save a summary of what was built, patterns used, and any issues encountered.

**Ontology update:** Use \`ontology_add\` to update the project status (e.g., entity "implementation" type "Phase" with properties {status: "complete", files: "N"}) and add a relation to the project entity.

**CRITICAL RULES:**
- Write ONE file per tool call — NEVER combine multiple files in a single response
- Keep each file under 500 lines. If longer, split into modules
- After writing ALL files, verify they exist with a single \`find . -name '*.ts' -o -name '*.js' -o -name '*.html' | sort\`` + runtimeInfo,
			},
			{
				key: "test", label: "🧪 Phase 4 — TEST", model: test.preferred, fallback: test.fallback,
				agent: loadAgentDef("test"),
				instruction: `You are the TEST agent. Verify the implementation.

**Context Retrieval:**
1. Use \`memory_search\` to find implementation notes from the CODE phase
2. Use \`ontology_query\` to understand the project architecture
3. Use this context to focus your testing

**Project Request:** ${description}

**Step 1:** Read \`.phi/plans/todo-*.md\` to know what was planned
**Step 2:** Read \`.phi/plans/progress-*.md\` to see what was done
**Step 3:** Run the code, check for errors, test key features
**Step 4:** Fix any errors you find
**Step 5:** Write test results to \`.phi/plans/test-${ts}.md\`

**Test report format:**
\`\`\`markdown
# Test Report

## Tests Executed
- [ ] Feature 1: Description - PASS/FAIL
- [ ] Feature 2: Description - PASS/FAIL

## Errors Found & Fixed
- Error: Description
  - Fix: What was done

## Manual Testing
- Tested: What was manually verified
- Result: Pass/Fail with details

## Final Status
✅ All tests pass / ❌ Issues remain
\`\`\`

**CRITICAL RULES:**
- NEVER run a server with \`&\` without cleanup. Always use: \`timeout 15 bash -c 'node src/index.js & PID=$!; sleep 2; curl ...; kill $PID'\`
- ALWAYS kill background processes after testing
- If a test hangs, use \`timeout\` to prevent deadlock
- NEVER put tool calls inside thinking blocks. Always use the proper JSON tool call format
- NEVER modify source code permanently for testing. Use environment variables: \`PORT=3001 node server.js\` instead of editing files
- NEVER create .env files with fake credentials. Use inline env vars: \`API_KEY=test node server.js\`
- For port conflicts, prefer: \`npx kill-port PORT\` (cross-platform)
- On Windows fallback: \`netstat -ano | findstr :PORT\` and \`taskkill /PID <pid> /F\`
- On Linux/Mac fallback: \`lsof -ti:PORT | xargs kill -9\`
- Always clean up after tests: kill background processes, remove temp files

**Anti-loop rule:** If the SAME test fails 3 times in a row with the same error after your fixes, STOP trying to fix it. Write the failure in your test report as "UNRESOLVED" and move on. Do not waste more than 3 iterations on the same issue.

After testing, use \`memory_write\` to save test results, bugs found, and lessons learned.

**Ontology update:** Use \`ontology_add\` to update the project status (e.g., entity "test-results" type "Phase" with properties {passed: "N", failed: "M", coverage: "X%"}) and add a relation to the project entity.` + runtimeInfo,
			},
			{
				key: "review", label: "🔍 Phase 5 — REVIEW", model: review.preferred, fallback: review.fallback,
				agent: loadAgentDef("review"),
				instruction: `You are the REVIEW agent. Final quality review.

**FIRST ACTIONS (MANDATORY — do these before anything else):**
1. Call \`memory_search\` to find all notes from previous phases (explore, plan, code, test)
2. Call \`ontology_query\` to understand the full project architecture and entity relationships

**Context Retrieval:**
3. Review all \`.phi/plans/*.md\` files for complete context

**Project Request:** ${description}

**Step 1:** Read all \`.phi/plans/*.md\` files
**Step 2:** Review code quality, security, performance
**Step 3:** Fix any issues found
**Step 4:** Write final report to \`.phi/plans/review-${ts}.md\`

**Review checklist:**
- Code quality: naming, structure, readability
- Security: input validation, error handling
- Performance: efficiency, resource usage
- Documentation: comments, README if needed
- Completeness: all requirements met

**Final report format:**
\`\`\`markdown
# Final Review

## Code Quality ✅/❌
- Structure: Good/Needs work
- Naming: Clear/Unclear
- Comments: Adequate/Missing

## Security ✅/❌
- Input validation: Present/Missing
- Error handling: Robust/Weak

## Performance ✅/❌
- Efficiency: Good/Could improve
- Resource usage: Optimal/Excessive

## Completeness ✅/❌
- All requirements met: Yes/No
- All files created: Yes/No

## Final Verdict
✅ Project ready for production / ❌ Issues need resolution
\`\`\`

After your review, use \`memory_write\` ONCE to save:
- Key lessons learned about this project type
- Patterns that worked well
- Common mistakes to avoid in future projects
Tag the note with relevant keywords for vector search.

**Important:** Write lessons-learned ONCE. Do not call memory_write twice with the same filename or duplicate content.

**Ontology enrichment:** After your review, use \`ontology_add\` to save your key findings:
- Add a "review-report" entity with type "Document"
- Add relations to the project: "reviews" → project, quality score as entity property
- Save any new architectural decisions or patterns discovered` + runtimeInfo,
			},
		];
	}

	/**
	 * Switch model for the current phase.
	 */
	async function switchModelForPhase(phase: OrchestratorPhase, ctx: any): Promise<string> {
		const available = ctx.modelRegistry?.getAvailable?.() || [];
		const preferred = available.find((m: any) => m.id === phase.model);
		const fallback = available.find((m: any) => m.id === phase.fallback);
		const target = preferred || fallback;

		if (target && target.id !== ctx.model?.id) {
			const switched = await pi.setModel(target);
			if (switched) return target.id;
		}
		return ctx.model?.id || phase.model;
	}

	/**
	 * Activate agent for a phase: set system prompt + restrict tools.
	 */
	function activateAgent(phase: OrchestratorPhase, ctx: any) {
		if (phase.agent) {
			// Save current tools for restoration
			if (!savedTools) {
				savedTools = pi.getActiveTools();
			}
			// Set agent's system prompt (will be injected via before_agent_start)
			activeAgentPrompt = phase.agent.systemPrompt;
			// Restrict tools to agent's allowed tools
			if (phase.agent.tools.length > 0) {
				// Always include memory tools in orchestration phases
				const memoryTools = ['memory_search', 'memory_write', 'memory_read', 'ontology_add', 'ontology_query'];
				const agentTools = [...phase.agent.tools, ...memoryTools.filter(t => !phase.agent.tools.includes(t))];
				activeAgentTools = agentTools;
				pi.setActiveTools(agentTools);
			}
		} else {
			activeAgentPrompt = null;
			activeAgentTools = null;
		}
	}

	/**
	 * Deactivate agent: restore tools, clear prompt override.
	 */
	function deactivateAgent() {
		activeAgentPrompt = null;
		activeAgentTools = null;
		if (savedTools) {
			pi.setActiveTools(savedTools);
			savedTools = null;
		}
	}

	/**
	 * Send the next phase in the queue.
	 */
	function setOrchestrationActive(active: boolean) {
		orchestrationActive = active;
		(globalThis as any).__phiOrchestrationActive = active;
	}

	function sendNextPhase(ctx: any) {
		if (phaseQueue.length === 0) {
			// All phases done — clean up and notify
			setOrchestrationActive(false);
			phasePending = false;
			deactivateAgent();
			if (phaseTimeoutId) { clearTimeout(phaseTimeoutId); phaseTimeoutId = null; }
			// Generate global final summary
			const totalPhases = 5; // always 5
			const elapsed = phaseStartTime ? Math.round((Date.now() - phaseStartTime) / 1000) : 0;
			const minutes = Math.floor(elapsed / 60);
			const seconds = elapsed % 60;
			ctx.ui.notify(`\n📊 **Orchestration Summary**\n` +
				`  Phases: ${totalPhases}/5 completed\n` +
				`  Duration: ${minutes}m ${seconds}s\n` +
				`  Check \`.phi/plans/\` for all reports`, "info");
			try {
				ctx.ui.notify(`\n✅ **All 5 phases complete!**`, "info");
			} catch {
				// Fallback: inject completion message into conversation stream
				try { pi.sendUserMessage(`✅ All 5 phases complete! The project is ready for review.`); } catch { /* best effort */ }
			}
			return;
		}

		const phase = phaseQueue.shift()!;
		phasePending = true;

		switchModelForPhase(phase, ctx).then((modelId) => {
			activateAgent(phase, ctx);
			const agentName = phase.agent?.name || phase.key;
			ctx.ui.notify(`\n${phase.label} → \`${modelId}\` (agent: ${agentName})`, "info");
			// Small delay to let the model switch settle, then send instruction
			setTimeout(() => pi.sendUserMessage(phase.instruction), 500);
			// Set phase timeout — abort if phase takes too long
			if (phaseTimeoutId) clearTimeout(phaseTimeoutId);
			phaseTimeoutId = setTimeout(() => {
				if (orchestrationActive && phasePending) {
					ctx.ui.notify(`\n⏰ **Phase timed out** (${MAX_PHASE_DURATION_MS / 60000} min limit). Skipping to next phase.`, "warning");
					phasePending = false;
					sendNextPhase(ctx);
				}
			}, MAX_PHASE_DURATION_MS);
		});
	}

	// ─── System Prompt Injection — Agent personas ────────────────────

	pi.on("before_agent_start", async (event, _ctx) => {
		if (!orchestrationActive || !activeAgentPrompt) {
			return { };
		}
		// Replace system prompt with the active agent's prompt
		return { systemPrompt: activeAgentPrompt };
	});

	// ─── Agent End Event — Phase Chaining ────────────────────────────
	// "agent_end" fires when the full agent loop completes (all tool calls
	// resolved, response fully generated). This is the ONLY reliable signal
	// that a phase has finished.
	//
	// Previous approach used "output" event which DOES NOT EXIST in Pi.
	// That's why phases 2-5 never executed.

	pi.on("agent_end", async (event, ctx) => {
		if (!orchestrationActive) return;
		// Allow completion even if phasePending was cleared by a duplicate event
		if (!phasePending) {
			// If queue is empty and orchestration is active, force completion
			if (phaseQueue.length === 0) {
				sendNextPhase(ctx);
			}
			return;
		}

		// Clear phase timeout on normal completion
		if (phaseTimeoutId) { clearTimeout(phaseTimeoutId); phaseTimeoutId = null; }

		// Build a structured summary of what happened in this phase
		// Instead of raw LLM text, extract concrete actions: files created/modified,
		// errors encountered, test results. This gives the next phase actionable context.
		const messages = event.messages || [];
		const filesWritten: string[] = [];
		const filesEdited: string[] = [];
		const errorsHit: string[] = [];
		const testResults: string[] = [];
		let toolCallCount = 0;

		for (const msg of messages) {
			// Pi uses role: "toolResult" instead of "tool"
			if (msg.role === 'tool' || msg.role === 'function' || msg.role === 'toolResult') {
				toolCallCount++;
				const content = Array.isArray(msg.content)
					? msg.content.map((c: any) => c.text || '').join('')
					: String(msg.content || '');
				const name = (msg as any).name || (msg as any).toolName || '';
				// Track writes
				if (name === 'write' && content.includes('Successfully wrote')) {
					const match = content.match(/wrote \d+ bytes to (.+)/);
					if (match) filesWritten.push(match[1]);
				}
				// Track edits
				if (name === 'edit' && !content.includes('ERR')) {
					const match = content.match(/edited (.+)/) || content.match(/in (.+)/);
					if (match) filesEdited.push(match[1]);
				}
				// Track errors — but filter out edit retries (old_text mismatch = normal retry, not error)
				if ((content.includes('ERR:') || content.includes('Error:') || content.includes('FAIL'))
					&& !content.includes('old text must match')
					&& !content.includes('The old text')
					&& !content.includes('oldText not found')
					&& !content.includes('old_text not found')) {
					const preview = content.slice(0, 150).replace(/\n/g, ' ');
					errorsHit.push(`${name}: ${preview}`);
				}
				// Track test results
				if (content.includes('PASS') || content.includes('✅') || content.includes('✗') || content.includes('❌')) {
					const lines = content.split('\n').filter(l => /PASS|FAIL|✅|❌|✗/.test(l));
					testResults.push(...lines.slice(0, 10));
				}
			}
		}

		// Detect API errors (401, auth failures) — abort workflow if found
		const hasAuthError = messages.some((msg: any) => {
			const content = typeof msg.content === 'string' ? msg.content : JSON.stringify(msg.content || '');
			return content.includes('401') && (content.includes('invalid access token') || content.includes('token expired') || content.includes('Unauthorized'));
		});
		if (hasAuthError || (toolCallCount === 0 && messages.length > 0)) {
			const errorMsg = hasAuthError ? 'API authentication error (401)' : 'Phase produced 0 tool calls — possible API or model error';
			ctx.ui.notify(`\n❌ **Orchestrator aborted:** ${errorMsg}\nCheck your API key and model configuration.`, "error");
			setOrchestrationActive(false);
			phasePending = false;
			deactivateAgent();
			if (phaseTimeoutId) { clearTimeout(phaseTimeoutId); phaseTimeoutId = null; }
			return;
		}

		// Build the summary
		const summaryParts: string[] = [];
		summaryParts.push(`Tool calls: ${toolCallCount}`);
		// Anti-loop guard: warn if tool calls are excessive
		if (toolCallCount > MAX_TOOL_CALLS_PER_PHASE) {
			summaryParts.push(`⚠️ WARNING: Phase used ${toolCallCount} tool calls (limit: ${MAX_TOOL_CALLS_PER_PHASE}). Possible loop detected.`);
		}
		if (filesWritten.length > 0) summaryParts.push(`Files created/written: ${filesWritten.join(', ')}`);
		if (filesEdited.length > 0) summaryParts.push(`Files edited: ${filesEdited.join(', ')}`);
		if (testResults.length > 0) summaryParts.push(`Test results:\n${testResults.join('\n')}`);
		if (errorsHit.length > 0) summaryParts.push(`Errors encountered: ${errorsHit.length}\n${errorsHit.slice(0, 5).join('\n')}`);

		// Verify mandatory tool usage
		const toolNames = messages
			.filter((m: any) => m.role === 'tool' || m.role === 'function' || m.role === 'toolResult')
			.map((m: any) => (m as any).name || (m as any).toolName || '');
		const hasMemorySearch = toolNames.includes('memory_search');
		const hasMemoryWrite = toolNames.includes('memory_write');
		if (!hasMemorySearch) summaryParts.push(`⚠️ Phase did NOT call memory_search (mandatory)`);
		if (!hasMemoryWrite) summaryParts.push(`⚠️ Phase did NOT call memory_write (mandatory)`);

		const phaseSummary = summaryParts.join('\n');

		// Inject structured summary into next phase
		if (phaseSummary && phaseQueue.length > 0) {
			phaseQueue[0].instruction += `\n\n**Previous phase summary:**\n${phaseSummary}`;
		}

		// Phase complete — chain to next
		phasePending = false;
		sendNextPhase(ctx);
	});

	// ─── /plan Command — Full workflow ───────────────────────────────

	pi.registerCommand("plan", {
		description: "Plan AND execute a project — 5 phases, each with its own model from routing.json",
		handler: async (args, ctx) => {
			const description = args.trim();

			if (!description) {
				ctx.ui.notify(`**Usage:** \`/plan <project description>\`

**Examples:**
  /plan Build a REST API for user authentication with JWT
  /plan Create a cyberpunk Pong browser game
  /plan Add test coverage to the payment module

**Other commands:**
  /plans — List all plans`, "info");
				return;
			}

			// Create plan files
			await ensurePlansDir();
			const ts = timestamp();
			const specFile = `spec-${ts}.md`;
			await writeFile(join(plansDir, specFile), `# ${description}\n\n**Created:** ${new Date().toLocaleString()}\n`, "utf-8");

			// Build phases with model assignments + agent definitions
			const phases = buildPhases(description);
			phaseQueue = phases.slice(1); // Queue phases 2-5
			setOrchestrationActive(true);
			phasePending = true;
			const firstPhase = phases[0];

			ctx.ui.notify(`📋 **Orchestrator started** — 5 phases with model routing + agent roles\n`, "info");

			// Show the plan
			for (const p of phases) {
				const agentName = p.agent?.name || p.key;
				const toolCount = p.agent?.tools.length || 0;
				ctx.ui.notify(`  ${p.label} → \`${p.model}\` (agent: ${agentName}, ${toolCount} tools)`, "info");
			}
			ctx.ui.notify("", "info");

			// Record orchestration start time for final summary
			phaseStartTime = Date.now();
			// Switch model and activate agent for first phase
			const modelId = await switchModelForPhase(firstPhase, ctx);
			activateAgent(firstPhase, ctx);
			const agentName = firstPhase.agent?.name || firstPhase.key;
			ctx.ui.notify(`${firstPhase.label} → \`${modelId}\` (agent: ${agentName})`, "info");
			setTimeout(() => pi.sendUserMessage(firstPhase.instruction), 200);
		},
	});

	// ─── /run Command — Re-execute existing plan ─────────────────────

	pi.registerCommand("run", {
		description: "Re-execute an existing plan (deprecated — use /plan instead)",
		handler: async (_args, ctx) => {
			ctx.ui.notify(
				"⚠️ `/run` is deprecated. Use `/plan <description>` to create and execute a new plan with the 5-phase orchestrator.",
				"warning",
			);
		},
	});

	// ─── /plans Command ──────────────────────────────────────────────

	pi.registerCommand("plans", {
		description: "List all project plans and their execution status",
		handler: async (_args, ctx) => {
			if (!existsSync(plansDir)) {
				ctx.ui.notify("No plans yet. Use `/plan <description>` to create and execute one.", "info");
				return;
			}

			const files = await readdir(plansDir);
			const specs = files.filter(f => f.startsWith("spec-") && f.endsWith(".md")).sort().reverse();

			if (specs.length === 0) {
				ctx.ui.notify("No plans found.", "info");
				return;
			}

			let output = `📁 **Project Plans** (${specs.length})\n\n`;

			for (const specFile of specs) {
				const ts = specFile.replace("spec-", "").replace(".md", "");
				const todoFile = `todo-${ts}.md`;
				const progressFile = `progress-${ts}.md`;

				try {
					const content = await readFile(join(plansDir, specFile), "utf-8");
					const titleMatch = content.match(/^# (.+)$/m);
					const title = titleMatch ? titleMatch[1] : specFile;
					const taskCount = (content.match(/\| \d+ \|/g) || []).length;
					const date = ts.replace(/_/g, " ").substring(0, 10);

					const hasTodo = files.includes(todoFile);
					const hasProgress = files.includes(progressFile);
					const status = hasProgress ? "🟢 executed" : hasTodo ? "🟡 planned" : "⚪ spec only";

					output += `📋 **${title}** (${date}) ${status}\n`;
					output += `   Spec: \`${specFile}\``;
					if (hasTodo) output += ` | Todo: \`${todoFile}\``;
					if (hasProgress) output += ` | Progress: \`${progressFile}\``;
					output += "\n";
					if (taskCount > 0) output += `   Tasks: ${taskCount}\n`;
					output += "\n";
				} catch {
					output += `📋 \`${specFile}\`\n\n`;
				}
			}

			output += `_Commands: \`/plan\` (create+execute), \`/run\` (re-execute), \`read .phi/plans/<file>\` (view)_`;
			ctx.ui.notify(output, "info");
		},
	});
}
